# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Interflora Styleguide
email: casper@adapt.dk
description: > # this means to ignore newlines until "baseurl:"
  Interflora.dk development guide. Helping new and old developers, designer etc. to maintain consistency across interflora.dk projects
baseurl: "/style-guide" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: casperjuel
github_username:  casperjuel

# Build settings
markdown: kramdown
